export const synonymMap: Record<string, string[]> = {
  "hello": ["hi", "hey", "greetings", "good day", "hello there"],
  "check": ["view", "see", "look at", "explore", "discover"],
  "offer": ["deal", "discount", "special", "package", "opportunity"],
  "new": ["latest", "recent", "fresh", "upcoming", "brand-new"],
  "message": ["text", "note", "update", "info", "notification"],
  "please": ["kindly", "could you", "if possible", "would you mind"],
  "important": ["critical", "essential", "urgent", "must-see", "vital"],
  "launch": ["start", "begin", "initiate", "kickoff", "commence"],
  "best": ["greatest", "top", "premium", "excellent", "superior"],
  "help": ["assist", "support", "guide", "aid"],
  "thanks": ["thank you", "much appreciated", "cheers"],
  "price": ["cost", "value", "amount", "rate"],
  "buy": ["purchase", "get", "order", "secure"],
  "join": ["sign up", "register", "become a member", "enter"],
  "limited": ["exclusive", "rare", "restricted", "short-term"],
  "fast": ["quick", "rapid", "speedy", "instant"],
  "free": ["complimentary", "no-cost", "gratuitous"],
  "contact": ["reach out to", "get in touch with", "connect with"],
  "business": ["company", "enterprise", "organization", "firm"],
  "leads": ["prospects", "potential clients", "targets", "contacts"],
  "bulk": ["mass", "large-scale", "group", "volume"],
  "verify": ["check", "validate", "confirm", "authenticate"]
};
